language: php
php:
  - 7.2
# env:
#   matrix:
#     - TRAVIS_NODE_VERSION="10"
#     - TRAVIS_NODE_VERSION="11"
#     - TRAVIS_NODE_VERSION="12"

matrix:
  fast_finish: true
# before_install:
#   - '. $HOME/.nvm/nvm.sh'
#   - nvm install $TRAVIS_NODE_VERSION
#   - nvm use $TRAVIS_NODE_VERSION
#   - npm install -g npm@latest
before_install:
  # Disable xdebug.
  - nvm install v14.7.0
  - nvm use v14.7.0
  - npm install -g npm@latest
install:
  - npm install
  - npm run setup
cache:
  directories:
    - '$HOME/.npm'
before_script:
  - php --version
  - node --version
  - npm --version
script:
  - npm run build:drupal --if-present
  - npm run build:pl --if-present

after_success: 
   - git add .
   - git commit -m "[skip travis] Adding particle dist/ assets"
  #  - git push https://bmartinez287:${GITHUB_API_KEY}@${GH_REF} HEAD:develop  #clownvary is my username on github, you need to use yourself , do not use travis or others.

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: ${GITHUB_API_KEY}  # Your GitHub token set in Travis CI console
  target_branch: develop        # Add this line - To push into GitHub master branch
  on:
    branch: develop
    condition: ${TRAVIS_COMMIT_MESSAGE} =~ ^(?!(Deploy)).+$
    # branch: staging            # Your GitHub repo default branch

