# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: [ develop ]
  pull_request_target:
    branches: [ develop ]
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
        ref: ${{ github.head_ref }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build:drupal --if-present
    - run: npm run build:pl --if-present
#     - run: npm test
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
    # Required
      commit_message: Dist folder
      branch: ${{ github.head_ref }}
    # - name: Commit changes
    #   uses: EndBug/add-and-commit@ts-only
    #   with:
    #     author_name: Bernardo Martinez
    #     author_email: xvk867@tennessee.edu
    #     message: "Compiling assets"
    #     add: "*"
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
